export const USER_ACTION_TYPES = {
  SET_USER: "SET_USER",
  FETCH_CURRENT_USER_START: "FETCH_CURRENT_USER_START",
  FETCH_CURRENT_USER_SUCCESS: "FETCH_CURRENT_USER_SUCCESS",
  FETCH_CURRENT_USER_FAILED: "FETCH_CURRENT_USER_FAILED",
};
